// Auto-generated by generate.py — Düzenlemeyin!
// Son güncelleme: 28.04.2026 12:24:39
// Katılımcı sayısı: 3

const SURVEY_DATA = [
  {
    "name": "Ca.. Ba.. So..",
    "timestamp": "2026-04-28 11:04:52.531000",
    "answers": [
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true
    ]
  },
  {
    "name": "Mu.. Ko.. Kö..",
    "timestamp": "2026-04-28 11:06:34.575000",
    "answers": [
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      false
    ]
  },
  {
    "name": "En.. Ka..",
    "timestamp": "2026-04-28 11:08:25.752000",
    "answers": [
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      true
    ]
  }
];
