"""
Dijital Gölgem — XLSX → data.js Dönüştürücü
Bu script, proje klasöründeki XLSX anket dosyasını okuyup
data.js dosyasına dönüştürür. Sonra index.html açıldığında
sonuçlar otomatik olarak görüntülenir.

Kullanım:
    python generate.py
"""

import openpyxl
import json
import os
import glob
import sys

# Encoding ayarı
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def find_xlsx_file():
    """Proje klasöründeki XLSX dosyasını bul."""
    patterns = [
        os.path.join(SCRIPT_DIR, "*.xlsx"),
    ]
    for pattern in patterns:
        files = glob.glob(pattern)
        if files:
            return files[0]
    return None

def parse_xlsx(filepath):
    """XLSX dosyasını oku ve katılımcı verilerini döndür."""
    wb = openpyxl.load_workbook(filepath)
    ws = wb.active

    headers = [cell.value for cell in ws[1]]
    participants = []
    participant_counter = 0

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, values_only=True):
        if not row or len(row) < 4:
            continue

        # İlk 3 sütun: Zaman damgası, KVKK onayı, Ad-Soyad
        timestamp = str(row[0]) if row[0] else ""
        # KVKK uyumluluğu: İsimler kısaltılarak anonimleştirildi
        # Örnek: "Mustafa Koray Kök" → "Mu.. Ko.. Kö.."
        participant_counter += 1
        raw_name = str(row[2]) if row[2] else f"Anonim {participant_counter}"
        name_parts = raw_name.strip().split()
        name = " ".join(p[:2] + ".." for p in name_parts)

        # Soru 1-15 (sütun 3-17, 0-indexed)
        answers = []
        for i in range(3, min(18, len(row))):
            val = str(row[i]).strip().lower() if row[i] else ""
            answers.append(val == "evet")

        # Eksik cevapları False olarak doldur
        while len(answers) < 15:
            answers.append(False)

        participants.append({
            "name": name,
            "timestamp": timestamp,
            "answers": answers
        })

    return participants

def generate_data_js(participants):
    """data.js dosyasını oluştur."""
    output_path = os.path.join(SCRIPT_DIR, "data.js")
    data_json = json.dumps(participants, ensure_ascii=False, indent=2)

    content = f"""// Auto-generated by generate.py — Düzenlemeyin!
// Son güncelleme: {__import__('datetime').datetime.now().strftime('%d.%m.%Y %H:%M:%S')}
// Katılımcı sayısı: {len(participants)}

const SURVEY_DATA = {data_json};
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✅ data.js başarıyla oluşturuldu!")
    print(f"   📁 Konum: {output_path}")
    print(f"   👥 Katılımcı sayısı: {len(participants)}")
    for i, p in enumerate(participants, 1):
        yes_count = sum(p['answers'])
        print(f"   {i}. {p['name']} — {yes_count}/15 Evet")
    print(f"\n🌐 Şimdi index.html dosyasını tarayıcıda açabilirsiniz.")

def main():
    print("🔍 XLSX dosyası aranıyor...")
    filepath = find_xlsx_file()

    if not filepath:
        print("❌ Proje klasöründe .xlsx dosyası bulunamadı!")
        print(f"   Lütfen XLSX dosyasını şu klasöre koyun: {SCRIPT_DIR}")
        sys.exit(1)

    print(f"📄 Dosya bulundu: {os.path.basename(filepath)}")
    print("📊 Veriler okunuyor...")

    participants = parse_xlsx(filepath)

    if not participants:
        print("❌ Dosyada katılımcı verisi bulunamadı!")
        sys.exit(1)

    generate_data_js(participants)

if __name__ == "__main__":
    main()
